[package]
name = "WebServer_1"
version = "0.1.0"
authors = ["namsoocho"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
regex = "1.3.7"
